### ISSUE TITLE
Should we include translation with an unknown source language?

### ISSUE THREAD

**Issue by domenic** [WICG/translation-api#1]
This is an open question discussed in [this part of the explainer](https://github.com/explainers-by-googlers/translation-api?tab=readme-ov-file#separating-language-detection-and-translation). The current proposal includes the ability to translate without specifying a source language, in which case the return type of `translate()` and `translateStreaming()` will change to include the detected language.

The alternative API is to require the web developer to specify the source language. If they don't know it, they can use the language detection part of the API first, and then separately use the translation API.

Both approaches have some precedents:

- [Google Cloud Translation API](https://cloud.google.com/translate/docs/reference/rest/v3beta1/projects/translateText), [DeepL Translate API](https://www.deepl.com/en/pro-api), and [Azure Translator API](https://learn.microsoft.com/en-us/azure/ai-services/translator/reference/v3-0-translate) allow unknown source languages
- [Google ML Kit](https://developers.google.com/ml-kit/language/translation/android) requires separate detect-then-translate steps

One factor to note is that bundling together language detection with translation requires the implementation to make a single best-guess at the source language. Whereas, separating the steps allows the detection step to return multiple possibilities, and then the developer can choose what to do with that information.

**Comment by MuraraAllan** [comment]
My opinion is that we do both ahhaha

I'm working with this right now, and from a dev perspective it is interesting to :

Dynamically .identify

But able to ``.translate({
  to: <opt><agent.intlanguage>
  from: <opt><agent.translateLanguageOption2>
})``

**Comment by domenic** [comment]
I can't really understand your examples, as they seem to be using some syntax other than JavaScript.

**Comment by domenic** [comment]
Closed by #15.
