### ISSUE TITLE
Not all languages create a Chrome TranslateKit component

### ISSUE THREAD

**Issue by MoChakmakchi** [WICG/translation-api#21]
Hi folks,

I am having an issue with finding new language packages in chrome://components/.

I tried using both canTranslate() and translate() on several language pairs, but so far I only got the following components to show up:
Chrome TranslateKit bn-en
Chrome TranslateKit en-es
Chrome TranslateKit en-ja

The pairs I tried are based on the table below of supported pairs from google docs:

[Supported language](https://docs.google.com/document/d/1bzpeKk4k26KfjtR-_d9OuXLMpJdRMiLZAOVNMuFIejk/edit?tab=t.0#heading=h.tf0fpc9s5xw2)
| Language Pair  | Language Pair  | Language Pair  | Language Pair  |
|----------------|----------------|----------------|----------------|
| en ⇔ ar        | en ⇔ bn       | en ⇔ de       | en ⇔ es        |
| en ⇔ fr        | en ⇔ hi       | en ⇔ it       | en ⇔ ja        |
| en ⇔ ko        | en ⇔ nl       | en ⇔ pl       | en ⇔ pt        |
| en ⇔ ru        | en ⇔ th       | en ⇔ tr       | en ⇔ vi        |
| en ⇔ zh        | en ⇔ zh-Hant  |                |                |

Any help would be appreciated!

PS. Wasn't sure if the issue is related to the API or Chrome, let me know if this is the wrong place please.

**Comment by domenic** [comment]
This appears to be an issue related to the Chrome implementation, and not the explainer. Such bugs are better filed at https://crbug.new/. Thanks!
