### ISSUE TITLE
`capabilities()` missing from translator API

### ISSUE THREAD

**Issue by cool-aid** [WICG/translation-api#26]
I'm on Chrome v133.0.6847.2.
My language detector API is returning capabilities() method, but translator API is missing the method. 
![translator_issue](https://github.com/user-attachments/assets/b90755f7-24a2-4f96-823e-4d07a7ca2db9)
Is that a bug?

**Comment by tomayac** [comment]
This is not a spec issue. It's simply Chrome's implementation not fully implementing the current spec draft yet.

**Comment by cool-aid** [comment]
> This is not a spec issue. It's simply Chrome's implementation not fully implementing the current spec draft yet.

So the methods are not ready to be consumed at this point?

**Comment by tomayac** [comment]
> So the methods are not ready to be consumed at this point?

Correct. It eventually will get implemented.

**Comment by tomayac** [comment]
The relevant Chromium bug is https://issues.chromium.org/issues/378992891 if you want to follow progress.
